### ISSUE TITLE
Añadir clase Enemigo

### ISSUE THREAD

**Issue by salvadorpuntozaragoza** [POOA-2017-2/Zombie-Attack#1]
@CristinaQuintero puedes añadir la clase Enemigo y añadirla al panel principal 
recuerda que debe tener los metodos de render y update donde render solo dibujara 
la imagen y update va a tener el  'x += dx'

**Comment by CristinaQuintero** [comment]
Me parece bien , es lo que se hablo en la tarde.

**Comment by CristinaQuintero** [comment]
## Listo Salvador! Cualquier duda me dices o avance que quieras que tenga en esta clase. 
Como lo miraste hoy solo el enemigo  tiene movimiento en la anchura de la ventana.

**Comment by salvadorpuntozaragoza** [comment]
Hola Cristina solo tenia unas dudas en el método run y el update creo que hacen lo mismo
El método update es el que debería tener las condiciones de cuando el mono se mueve para la izquierda o derecha, el método run solo se encarga de cambiar la imagen que se va a dibujar 

También inicializa la imagen del enemigo en el constructor ya que si la inixializas en el método render se va a dibujar la misma imagen

**Comment by CristinaQuintero** [comment]
De hecho cuando me lo dijiste me percate de que  update solo daba el valor actual  de eje X . en cambio el run hace lo mismo pero ejecuta que el movimiento del enemigo sea  consecutivo  de izquierda a derecha , no te preocupes entiendo lo que me  escribistes y  estare trabajando en ello.

**Comment by CristinaQuintero** [comment]
Salvador , cheque el código y  Emmanuel hizo la parte que  querias que hiciera con la clase.

**Comment by salvadorpuntozaragoza** [comment]
Muchachos sigo sin entender algunas cosas
1. Por qué la clase extiende de jpanel 
2.que hace el método Run 
3.por qué inicial izan las imágenes en el método render y no en el método constructor

**Comment by CristinaQuintero** [comment]
**1.-**
Bueno salvador mi respuesta de ello es que al principio que yo hice la clase enemigo, yo lo quise hacer de la forma que yo entiendo para hacer una animación en java utilizando un jpanel para la animación y un Jframe para mostrarloy es por ello que hice  la clase ZombieAttack lo recuerdas con las ventana principal y el boton jugar que mandaba a llamar tu clase game para iniciar el juego ;Yo no quise modificar nada de tu clase Game por que sabia que tu habias creado varias clases  para hacer funcionar tu clase jugador, pero cheque que tu habias utilizado dentro de la clase game la forma de hacerlo con CANVAS , y tu clase display es tu Jframe que muestra tus animaciones en una ventana. Al principio yo no  te entendía

**2.-**
 el método run  esta el codigo para  que el enemigo  se mueva en el eje x  sin parar , poniendo las condiciones  mostradas.
**3.-**
y render para mi antes era  el método paint  que funciona para cargar  la animación utilizando la clase image con su getImage() y el drawImage para mostrarlo   y , pero luego que mire tu código , método render era prácticamente un metodo paint. y solo le cambie el nombre  para  poder llamar este método en la clase game al momento de yo crear un objeto de Enemigo y que esto funcionaba. 

Al principio también tenia muchas dudas de la forma que tu lo hiciste ,por eso opte por hacerlo como yo podía entenderlo , pero era mi forma de poder aportar algo al proyecto  en esa semana para  poder  avanzar  un poco y que fuera positiva nuestro avance . que en realidad  me costo para  poder juntarlo con lo tuyo y que ustedes lo miraran.

por mi parte  haré  las modificación como tu lo mencionaste y así poder estar utilizando la forma que hicistes el jugador para  tener un orden en el código. Pero las tendria en la mañana del domingo.
